#some dummy data
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Thomas','SomeImage.png','Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Alex','SomeImage.png','Really Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Peter','SomeImage.png','Really Really Great Image','parametersLater');


INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Thomas','SomeImage2.png','Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Alex','SomeImage2.png','Really Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Peter','SomeImage2.png','Really Really Great Image','parametersLater');


INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Thomas','SomeImage3.png','Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Alex','SomeImage3.png','Really Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Peter','SomeImage3.png','Really Really Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Thomas','SomeImage3.png','Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Alex','SomeImage3.png','Really Great Image','parametersLater');
INSERT INTO COMMENT (AUTHOR,IMAGEID,COMMENT_CONTENT,PROCESSING_PARAMETERS) VALUES('Peter','SomeImage3.png','Really Really Great Image','parametersLater');