drop table COMMENT;

CREATE TABLE COMMENT (
	ID INT NOT NULL auto_increment,
	AUTHOR VARCHAR(255) NOT NULL,
	IMAGEID VARCHAR(255) NOT NULL,
	COMMENT_CONTENT VARCHAR(1024),
	PROCESSINGPARAMETERS VARCHAR(1024),
	CONSTRAINT COMMENT_PK PRIMARY KEY (ID)
);
